service: myTestService
provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  environment:
    FRONTEND_BASE_URL: ${param:frontendBaseUrl,''}
    ALLOWED_ORIGIN: ${param:allowedOrigins,''}
    PARAMETER_STORE_NAME: /ecommerce/${opt:stage,''}/secrets
    EMAIL_FROM: ${param:emailFrom,''}
    ADMIN_EMAILS: ${param:adminEmails,''}
    DYNAMODB_TABLE_NAME: ecommerce-${opt:stage,''}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:Query"
            - "dynamodb:GetItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource:
            Fn::Join:
              - ":"
              - - "arn:aws:dynamodb"
                - Ref: "AWS::Region"
                - Ref: "AWS::AccountId"
                - table/ecommerce-${opt:stage,''}
        - Effect: "Allow"
          Action:
            - "ssm:DescribeParameters"
            - "ssm:GetParameter"
          Resource:
            Fn::Join:
              - ":"
              - - "arn:aws:ssm"
                - Ref: "AWS::Region"
                - Ref: "AWS::AccountId"
                - parameter/ecommerce/${opt:stage,''}/secrets
        - Effect: "Allow"
          Action:
            - "kms:Decrypt"
          Resource:
            Fn::Join:
              - ":"
              - - "arn:aws:kms"
                - Ref: "AWS::Region"
                - Ref: "AWS::AccountId"
                - key/${param:ssmEncryptionKeyId,''}
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
          Resource: "*"
functions:
  hello:
    handler: bin/hello
  api:
    handler: bin/api
    events:
      - http:
          path: /products
          method: get
      - http:
          path: /categories
          method: get
      - http:
          path: /admin/products
          method: post
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /admin/categories
          method: post
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /admin/inventory
          method: put
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /admin/product/{productId}
          method: put
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /me/cart
          method: get
      - http:
          path: /me/cart
          method: put
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /product/{id}
          method: get
      - http:
          path: /checkout
          method: post
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /webhooks/stripe
          method: post
      - http:
          path: /testEmail
          method: get
package:
  patterns:
    # we exclude everything
    - '!*/**'
    # except: everything that is inside bin directory
    - 'bin/*'